# Generated by Django 3.2.4 on 2021-07-13 12:20

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('age', models.IntegerField(default=18, null=True)),
                ('address', models.CharField(max_length=60, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15, unique=True)),
                ('birthdate', models.DateField(default=datetime.date.today)),
                ('enroll_date', models.DateField(default=datetime.date.today, null=True)),
                ('graduate_date', models.DateField(default=datetime.date.today, null=True)),
                ('groups_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='groups.group')),
            ],
        ),
    ]
