# Generated by Django 3.2.4 on 2021-07-08 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teachers_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='birthdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='age',
            field=models.IntegerField(default=18, null=True),
        ),
    ]
