# Generated by Django 3.2.4 on 2021-06-23 20:51

import django.core.validators
from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('age', models.IntegerField(default=18, null=True, validators=[groups.validators.adult_validator])),
                ('address', models.CharField(max_length=60, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15, unique=True)),
                ('groups_number', models.IntegerField(null=True)),
            ],
        ),
    ]
