# Generated by Django 3.2.4 on 2021-06-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.ImageField(default=18, upload_to='')),
                ('address', models.CharField(max_length=60)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
    ]
