# Generated by Django 3.2.4 on 2021-06-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='phone',
            new_name='groups_number',
        ),
    ]
