# Generated by Django 3.2.4 on 2021-06-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_phone_groups_groups_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='address',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='age',
            field=models.ImageField(default=18, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='groups',
            name='groups_number',
            field=models.IntegerField(null=True),
        ),
    ]
