# Generated by Django 3.2.4 on 2021-06-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20210609_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='age',
            field=models.IntegerField(default=18, null=True),
        ),
    ]
