# Generated by Django 3.2.4 on 2021-06-22 10:24

import django.core.validators
from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_groups_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='phone_number',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groups',
            name='age',
            field=models.IntegerField(default=18, null=True, validators=[groups.validators.adult_validator]),
        ),
        migrations.AlterField(
            model_name='groups',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='groups',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='groups',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
